version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/simple_node
    environment:
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD 
    steps:
      - checkout
      - setup_remote_docker

  test:
    docker:
      - image: cimg/simple_node
    steps:
      - checkout
      - setup_remote_docker

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test