version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce
      - setup_remote_docker
      - run: docker build -t my-container .
      - run: docker run my-container

  test:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce
      - setup_remote_docker
      - run: docker build -t my-container .
      - run: docker run my-container

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test