version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/simple_node
    steps:
      - checkout
      - run:
        name: Authenticate with docker hub
        command: |
        echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
      - setup_remote_docker

  test:
    docker:
      - image: cimg/simple_node
    steps:
      - checkout
      - run:
        name: Authenticate with docker hub
        command: |
        echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
      - setup_remote_docker

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test