version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: simple_node
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - setup_remote_docker

  test:
    docker:
      - image: simple_node
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - setup_remote_docker

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test