version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Authenticate with Docker Hub
          command: docker login -u "$DOCKER_USERNAME" -u "$DOCKER_PASSWORD"
      - setup_remote_docker

  test:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Authenticate with Docker Hub
          command: docker login -u "$DOCKER_USERNAME" -u "$DOCKER_PASSWORD"
      - setup_remote_docker

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test