version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker client
          command: echo docker --version
      - run: echo docker build -t my-container .
      - run: echo docker run my-container

  test:
    docker:
      - image: huutocdai/simple_node:latest
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker client
          command: echo docker --version
      - run: echo docker build -t my-container .
      - run: echo docker run my-container

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test