version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: huutocdai/simple_node:latest
      - image: cimg/base:2023.06
    steps:
      - checkout
      # Authenticate with Docker Hub using environment variables
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker client
          command: docker --version
      - run: docker build -t my-container .
      - run: docker run my-container
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build